### ISSUE TITLE
Vanish problem

### ISSUE THREAD

**Issue by JuanDenis** [AuracleTech/NoNameTag#3]
The plugin works fine, the problem is that when I add this plugin the vanish stops working. Is there a solution for this?

**Comment by AuracleTech** [comment]
Two options, both of which puts you on a quest because vanish's code is causing the issue.

1. You would need to find another vanish plugin that doesn't rely scoreboard teams. Not ideal.
3. The scoreboard teams system is the only solution to remove players nametags.
So vanish probably use it to.
However they do not need to remove the team of *all players*.
Instead they should toggle vanish on a specified user and then toggle back to what it was when finished.
I recommend contacting the vanish dev team asking them about the reason they do it this way (or refer them here).
This would increase their compatibility with lots of plugins too!

**Comment by JuanDenis** [comment]
great, thanks!
